spring:
  application:
    name: springboot-kafka-example
  kafka:
    bootstrap-servers: "localhost:9093"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer